# Generated by Django 5.2.3 on 2025-06-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='is_translated',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='translated_content',
            field=models.TextField(null=True),
        ),
    ]
